### ISSUE TITLE
Itinerário aparece incorretamente

### ISSUE THREAD

**Issue by macecchi** [RioBus/ios#16]
O último ponto liga com o primeiro, fechando o caminho do itinerário. 
![simulator screen shot aug 5 2015 7 19 02 pm](https://cloud.githubusercontent.com/assets/5282467/9099388/b103c468-3ba6-11e5-9f68-c60877863b85.png)

**Comment by marco-jardim** [comment]
Na verdade isso acontece em todas as plataformas...
