### ISSUE TITLE
Sugestões de Design/Usabilidade

### ISSUE THREAD

**Issue by danielgmrs** [RioBus/ios#21]
Tenho certeza que já devem estar implementando no iOS o icone verde/amarelo/vermelho igual no site, é realmente muito útil.
Outra sugestão é criar um raio em cada onibus onde ele poderia estar de acordo com sua velocidade/tempo atualização nos icones amarelos, já que nos vermelhos seria muito desatualizado e verde geralmente é no mesmo minuto.
O botão da 'cobrinha' onde troca o itinerário do ônibus não é muito intuitivo, pois demorar um tempo pra descobrir que era um botão e que possuía essa funcionalidade. Outro detalhe que incomoda é que depois que aperta, não é possível ver as duas opções novamente.

**Comment by macecchi** [comment]
Oi, @danielgmrs! Obrigado pelo seu feedback! Sugestões devidamente anotadas :)

O botão da 'cobrinha' é uma alternativa na verdade. Se você clicar no nome do destino desejado ele já seleciona. Mas realmente não tem como selecionar novamente os dois, e isso é algo que eu irei alterar, algo que eu não tinha pensado sobre mesmo!

Vou criar outro issue separado aqui pra fazer isso.

**Comment by macecchi** [comment]
Estou fechando este issue e darei continuidade às sugestões em cada issue separado.
